#!/usr/bin/env bash
set -e

if [ "$1" = "--debug" ]; then
  export TSGC_DEBUG=1
  shift
fi

if [ -n "$TSGC_DEBUG" ]; then
  export PS4='+ [${BASH_SOURCE##*/}:${LINENO}] '
  set -x
fi

READLINK=$(type -p greadlink readlink | head -1)
if [ -z "$READLINK" ]; then
  echo "tmux sgc: cannot find readlink - are you missing GNU coreutils?" >&2
  exit 1
fi

resolve_link() {
  $READLINK "$1"
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

bin_path="$(abs_dirname "$0")"

command="$1"
case "$command" in
"" | "-h" | "--help" )
  cat "${bin_path}/README.md" >&2
  ;;
* )
  command_path="$(command -v "${bin_path}/tsgc-$command" || true)"
  if [ -z "$command_path" ]; then
    echo "tmux sgc: no such command \`$command'" >&2
    exit 1
  fi

  shift 1
  exec "$command_path" "$@"
  ;;
esac

exit 0
